/**
 * Export utilities for governance reports
 */

export interface ExportData {
  artifacts: {
    total: number;
    breaking: number;
    changed: number;
    impacted: number;
    verified: number;
  };
  decisions: Array<{
    change_id: string;
    decision: string;
    risk_level: string;
    timestamp: string;
    reasoning: string[];
    human_feedback: {
      outcome: string;
      notes?: string;
    };
  }>;
  generatedAt: string;
}

/**
 * Export data as JSON file
 */
export function exportAsJSON(data: ExportData, filename?: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  downloadBlob(blob, filename || `dotto-report-${getTimestamp()}.json`);
}

/**
 * Export data as Markdown report
 */
export function exportAsMarkdown(data: ExportData, filename?: string): void {
  const md = generateMarkdownReport(data);
  const blob = new Blob([md], { type: "text/markdown" });
  downloadBlob(blob, filename || `dotto-report-${getTimestamp()}.md`);
}

/**
 * Generate a Markdown formatted report
 */
function generateMarkdownReport(data: ExportData): string {
  const lines: string[] = [];

  // Header
  lines.push("# Dotto Governance Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date(data.generatedAt).toLocaleString()}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Count |");
  lines.push("|--------|-------|");
  lines.push(`| Total Artifacts | ${data.artifacts.total} |`);
  lines.push(`| Breaking Changes | ${data.artifacts.breaking} |`);
  lines.push(`| Changed | ${data.artifacts.changed} |`);
  lines.push(`| Impacted | ${data.artifacts.impacted} |`);
  lines.push(`| Verified | ${data.artifacts.verified} |`);
  lines.push("");

  // Risk Assessment
  if (data.artifacts.breaking > 0) {
    lines.push("### Risk Assessment");
    lines.push("");
    lines.push(
      `**Blast Radius:** ${data.artifacts.breaking + data.artifacts.impacted} nodes potentially affected`
    );
    lines.push("");
  }

  // Decision History
  if (data.decisions.length > 0) {
    lines.push("## Decision History");
    lines.push("");

    data.decisions.forEach((decision, idx) => {
      lines.push(`### ${idx + 1}. ${decision.change_id}`);
      lines.push("");
      lines.push(`- **Decision:** ${decision.decision.toUpperCase()}`);
      lines.push(`- **Risk Level:** ${decision.risk_level}`);
      lines.push(`- **Date:** ${new Date(decision.timestamp).toLocaleString()}`);
      lines.push("");

      if (decision.reasoning.length > 0) {
        lines.push("**Reasoning:**");
        decision.reasoning.forEach((r) => lines.push(`- ${r}`));
        lines.push("");
      }

      lines.push(`**Human Authority:** ${formatHumanFeedback(decision.human_feedback)}`);
      if (decision.human_feedback.notes) {
        lines.push(`> "${decision.human_feedback.notes}"`);
      }
      lines.push("");
    });
  } else {
    lines.push("## Decision History");
    lines.push("");
    lines.push("*No decisions recorded yet.*");
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Generated by Dotto - AI Production Governance*");

  return lines.join("\n");
}

/**
 * Format human feedback outcome for display
 */
function formatHumanFeedback(feedback: { outcome: string; override_decision?: string }): string {
  if (feedback.outcome === "accepted") {
    return "Accepted";
  }
  if (feedback.outcome === "overridden") {
    if (feedback.override_decision === "block") {
      return "Blocked (Override)";
    }
    if (feedback.override_decision === "approve") {
      return "Approved (Override)";
    }
    return "Overridden";
  }
  return feedback.outcome;
}

/**
 * Get timestamp for filename
 */
function getTimestamp(): string {
  const now = new Date();
  return now.toISOString().slice(0, 19).replace(/[:-]/g, "").replace("T", "-");
}

/**
 * Trigger file download
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
